config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  post "tasks/:id/toggle", to: "tasks#toggle"
  get "homes/stimulas"
  get "homes/modal"
  get "homes/faq"
  get "homes/tab"
  get "homes/list"
  get "homes/menu"
  root "homes#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def home
	end
	def modal
	end
	def faq
	end
	def tab
	end
	def list
	end
	def stimulas
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
      @tasks = Task.all
      @task = Task.new
    end
  
    def create
      @task = Task.new(task_params)
  
      respond_to do |format|
        if @task.save
          format.html { redirect_to tasks_url, notice: "Task was successfully created" }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    def edit
      @task = Task.find(params[:id])
    end
  
    def update
      @task = Task.find(params[:id])
  
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @task = Task.find(params[:id])
      @task.destroy
  
      redirect_to tasks_url, notice: "Task was successfully deleted."
    end
  
    def toggle
      @task = Task.find(params[:id])
      @task.update(completed: params[:completed])
  
      render json: { message: "Success" }
    end
  
    private
  
    def task_params
      params.require(:task).permit(:description)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/homes/faq.html.erb
<main>
<h1 class="faq-heading">FAQ'S</h1>
<section class="faq-container">
	<div class="faq-one">
		<!-- faq question -->
		<h1 class="faq-page">What is an FAQ Page?</h1>
		<!-- faq answer -->
		<div class="faq-body">
			<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit saepe sequi, illum facere
				necessitatibus cum aliquam id illo omnis maxime, totam soluta voluptate amet ut sit ipsum
				aperiam.
				Perspiciatis, porro!</p>
		</div>
	</div>
	<hr class="hr-line">
	<div class="faq-two">
		<!-- faq question -->
		<h1 class="faq-page">Why do you need an FAQ page?</h1>
		<!-- faq answer -->
		<div class="faq-body">
			<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit saepe sequi, illum facere
				necessitatibus cum aliquam id illo omnis maxime, totam soluta voluptate amet ut sit ipsum
				aperiam.
				Perspiciatis, porro!</p>
		</div>
	</div>
	<hr class="hr-line">
	<div class="faq-three">
		<!-- faq question -->
<h1 class="faq-page">Does it improves the user experience of a website?</h1>
		<!-- faq answer -->
		<div class="faq-body">
			<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Velit saepe sequi, illum facere
				necessitatibus cum aliquam id illo omnis maxime, totam soluta voluptate amet ut sit ipsum
				aperiam.
				Perspiciatis, porro!</p>
		</div>
	</div>
</section>
</main>

<script>
var faq = document.getElementsByClassName("faq-page");
var i;

for (i = 0; i < faq.length; i++) {
    faq[i].addEventListener("click", function () {
        /* Toggle between adding and removing the "active" class,
        to highlight the button that controls the panel */
        this.classList.toggle("active");

        /* Toggle between hiding and showing the active panel */
        var body = this.nextElementSibling;
        if (body.style.display === "block") {
            body.style.display = "none";
        } else {
            body.style.display = "block";
        }
    });
}
</script>

<style>
body{
    font-family: 'Work Sans', sans-serif;
}
.faq-heading{
    border-bottom: #777;
    padding: 20px 60px;
}
.faq-container{
display: flex;
justify-content: center;
flex-direction: column;

}
.hr-line{
  width: 60%;
  margin: auto;
  
}
/* Style the buttons that are used to open and close the faq-page body */
.faq-page {
    /* background-color: #eee; */
    color: #444;
    cursor: pointer;
    padding: 30px 20px;
    width: 60%;
    border: none;
    outline: none;
    transition: 0.4s;
    margin: auto;

}
.faq-body{
    margin: auto;
    /* text-align: center; */
   width: 50%; 
   padding: auto;
   
}


/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active,
.faq-page:hover {
    background-color: #F9F9F9;
}

/* Style the faq-page panel. Note: hidden by default */
.faq-body {
    padding: 0 18px;
    background-color: white;
    display: none;
    overflow: hidden;
}

.faq-page:after {
    content: '\02795';
    /* Unicode character for "plus" sign (+) */
    font-size: 13px;
    color: #777;
    float: right;
    margin-left: 5px;
}

.active:after {
    content: "\2796";
    /* Unicode character for "minus" sign (-) */
}
</style>

app/views/homes/home.html.erb
<h1>5 Javascript Projects You Need TO Build Right Now</h1>
<ul>
	
	<li>
		<%=link_to "How to create a Modal",homes_modal_path%>
	</li>
	<li>
	<%=link_to "How to create a FAQ page",homes_faq_path%>
	</li>
	<li>
	<%=link_to "How to Create a Tab that display different Content",homes_tab_path%>
	</li>
	<li>
	<%=link_to "How to create a grocery list",homes_list_path%>
	</li>
	<li>
	<%=link_to "Using Stimulas in Rails",homes_stimulas_path%>
	</li>
</ul>

app/views/homes/list.html.erb
<div id="myDIV" class="header">
  <h2>GroceryList</h2>
  <input type="text" id="myInput" placeholder="Title...">
  <span onclick="newElement()" class="addBtn">Add</span>
</div>

<ul id="myUL">
  <li>Hit the gym</li>
  <li class="checked">Pay bills</li>
  <li>Meet George</li>
  <li>Buy eggs</li>
  <li>Read a book</li>
  <li>Organize office</li>
</ul>

<script>

var myNodelist = document.getElementsByTagName("LI");
var i;
for (i = 0; i < myNodelist.length; i++) {
  var span = document.createElement("SPAN");
  var txt = document.createTextNode("\u00D7");
  span.className = "close";
  span.appendChild(txt);
  myNodelist[i].appendChild(span);
}


var close = document.getElementsByClassName("close");
var i;
for (i = 0; i < close.length; i++) {
  close[i].onclick = function() {
    var div = this.parentElement;
    div.style.display = "none";
  }
}


var list = document.querySelector('ul');
list.addEventListener('click', function(ev) {
  if (ev.target.tagName === 'LI') {
    ev.target.classList.toggle('checked');
  }
}, false);


function newElement() {
  var li = document.createElement("li");
  var inputValue = document.getElementById("myInput").value;
  var t = document.createTextNode(inputValue);
  li.appendChild(t);
  if (inputValue === '') {
    alert("You must write something!");
  } else {
    document.getElementById("myUL").appendChild(li);
  }
  document.getElementById("myInput").value = "";

  var span = document.createElement("SPAN");
  var txt = document.createTextNode("\u00D7");
  span.className = "close";
  span.appendChild(txt);
  li.appendChild(span);

  for (i = 0; i < close.length; i++) {
    close[i].onclick = function() {
      var div = this.parentElement;
      div.style.display = "none";
    }
  }
}
</script>
<style>
* {
  box-sizing: border-box;
}


ul {
  margin: 0;
  padding: 0;
}


ul li {
  cursor: pointer;
  position: relative;
  padding: 12px 8px 12px 40px;
  background: #eee;
  font-size: 18px;
  transition: 0.2s;

  
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}


ul li:nth-child(odd) {
  background: #f9f9f9;
}

ul li:hover {
  background: #ddd;
}


ul li.checked {
  background: #888;
  color: #fff;
  text-decoration: line-through;
}


ul li.checked::before {
  content: '';
  position: absolute;
  border-color: #fff;
  border-style: solid;
  border-width: 0 2px 2px 0;
  top: 10px;
  left: 16px;
  transform: rotate(45deg);
  height: 15px;
  width: 7px;
}


.close {
  position: absolute;
  right: 0;
  top: 0;
  padding: 12px 16px 12px 16px;
}

.close:hover {
  background-color: #f44336;
  color: white;
}


.header {
  background-color: #f44336;
  padding: 30px 40px;
  color: white;
  text-align: center;
}


.header:after {
  content: "";
  display: table;
  clear: both;
}


input {
  margin: 0;
  border: none;
  border-radius: 0;
  width: 75%;
  padding: 10px;
  float: left;
  font-size: 16px;
}


.addBtn {
  padding: 10px;
  width: 25%;
  background: #d9d9d9;
  color: #555;
  float: left;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}

.addBtn:hover {
  background-color: #bbb;
}
</style>

app/views/homes/modal.html.erb
<h1>How to create a Modal</h1>
<!-- hero -->
    <header class="hero">
      <div class="banner">
        <h1>modal project</h1>
        <button class="btn modal-btn">
          open modal
        </button>
      </div>
    </header>
    <!-- modal -->
    <div class="modal-overlay">
      <div class="modal-container">
        <h3>modal content</h3>
        <button class="close-btn"><i class="fas fa-times"></i></button>
      </div>
    </div>


<script>
const modalBtn = document.querySelector(".modal-btn");
const modal = document.querySelector(".modal-overlay");
const closeBtn = document.querySelector(".close-btn");

modalBtn.addEventListener("click", function () {
  modal.classList.add("open-modal");
});
closeBtn.addEventListener("click", function () {
  modal.classList.remove("open-modal");
});
</script>

app/views/homes/stimulas.html.erb
<h1>
How to Work with Stimulas?
</h1>

<ol>
    <li>
    Three atribute you need to set if working with stimulas i.e <b>Controller, Action and Targets</b>
    </li>
    <li></li>
    
</ol>

<%=link_to "Stimulas App",tasks_path%>
<style>
li {
    margin: 17px;
}

</style>

app/views/homes/tab.html.erb
<div class = "tab">
    <button class = "btnlinks" onclick="opentab(event,'London')">London</button>
    <button class = "btnlinks" onclick="opentab(event,'Paris')">Paris</button>
    <button class = "btnlinks" onclick="opentab(event,'Newyork')">Newyork</button>
</div>


<div id = "London" class = "tabcontent">
<h3>London</h3>
<p>Lorem Ipsum</p>
</div>

<div id = "Paris" class = "tabcontent">
<h3>Paris</h3>
<p>Lorem Ipsum 2</p>
</div>

<div id = "Newyork" class = "tabcontent">
<h3>NewYork</h3>
<p>Lorem Ipsum 3</p>
</div>

<script>
    function opentab(evt,cityname)
    {
        var i, tabcontent, btnlinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
        }
        btnlinks = document.getElementsByClassName("btnlinks");
  for (i = 0; i < btnlinks.length; i++) {
    btnlinks[i].className = btnlinks[i].className.replace(" active", "");
  }


  document.getElementById(cityname).style.display = "block";
  evt.currentTarget.className += " active";
    }
</script>









<style>
.tab{
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #f1f1f1;
}

.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
}

.tab button:hover {
  background-color: #ddd;
}

.tab button.active {
  background-color: #ccc;
}

.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jscript</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
    <div>
      <%= form.text_field :description, placeholder: "Add new task"%>
      <%= form.submit "Save" %>
    </div>
  <% end %>

app/views/tasks/_task.html.erb
<div >
  <%= form_with(model: task) do |form| %>
    <%= form.check_box :completed,
                       data: {
                         id: task.id,
                         action: "tasks#toggle"
                       }
                        %>
    <%= task.description %>
  <% end %>

  <%= link_to "Edit", edit_task_path(task)
  %>
  <div>
    <%= button_to "Delete", task_path(task),
                  method: :delete,
                  data: { action: "tasks#delete" } %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div>
  <h1>Editing Task</h1>

  <div id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Never Mind", tasks_path%>
  </div>
</div>

app/views/tasks/index.html.erb
<% if notice.present? %>
  <p id="notice">
    <%= notice %>
  </p>
<% end %>

<h1>Task Manager</h1>

<div>
  <%= render "form", task: @task %>
</div>

<div id="tasks">
  <h1>Tasks</h1>

  <div data-controller="tasks">
    <%= render @tasks %>
  </div>
</div>